### ISSUE TITLE
Jenkinsflow returns SUCCESS when flow has failed

### ISSUE THREAD

**Issue by lechat** [lhupfeldt/jenkinsflow#25]
Hi, Lars

One of the jobs in flow has failed, but the job, that runs flow itself shows that flow failed, but still returns success. How do I fail flow job when flow has failed?

```
--- Final status ---
serial flow: [
   serial flow: [
      job: 'JOB_1' SUCCESS
      job: 'LONG_JOB' FAILURE  http://jenkins/jenkins/job/LONG_JOB/208/console
      job: 'JOB_2' UNKNOWN - IDLE 
   ]

   parallel flow: (
      serial flow: [
         job: 'JOB_3' UNKNOWN - IDLE 
         job: 'JOB_4' UNKNOWN - IDLE 
      ]

      serial flow: [
         job: 'JOB_5' UNKNOWN - IDLE 
         job: 'JOB_6' UNKNOWN - IDLE 
      ]

   )

]

Finished: SUCCESS
```

Note that flow failed, but ``jenkinsflow`` still returns "SUCCESS" instead of "FAILURE".

Is there something I miss?

**Comment by lechat** [comment]
This code in ``flow.py::_TopLevelControllerMixin.wait_for_jobs()`` is never executed... 

```
if self.result == BuildResult.UNSTABLE:
            set_build_result(self.username, self.password, 'unstable', direct_url=self.top_flow.direct_url)
```
Also, ``set_build_result()`` relies on Jenkins CLI jar to be in ``$WORKSPACE``, but I can't see what triggers ``download_cli()`` anywhere in the code...

**Comment by lechat** [comment]
The version from ``master`` fails build properly, but I can't use it because it has numerous places, where it refers to ``self.result.name`` and ``self.result`` is ``int``...

flow.py: lines 679, 365, 447, 316

**Comment by lhupfeldt** [comment]
Hi Aleksey,

The line numbers you show do not seem to point to any lines <code>with self.result.name</code>!

What do you mean by you can't use it beause...? Are you seing an actual error or are you assuming there is an error? I'm pretty sure result is not <code>int</code>, it is an <code>Enum</code> value. Maybe it is pylint telling you that it is <code>int</code>? pylint's understanding of <code>Enum</code> is not very good.

Regarding <code>if self.result == BuildResult.UNSTABLE:</code> not being executed: <code>BuildResult.UNSTABLE</code> normally only happens when using test plugins (junit) where test cases fail. A failed job will have <code>BuildResul.FAILURE</code>. You can ask jenkinsflow to propagate <code>BuildResul.UNSTABLE</code> from a failed job to the job running the flow, or you can use <code>jenkinflow set_build_result ...</code> from inside a job shell step to change the result to <code>BuildResult.UNSTABLE</code>.

Is the testsuite running correctly against your version of Jenkins?

**Comment by lhupfeldt** [comment]
Hi Aleksey,

Any more info about your issue?

**Comment by lhupfeldt** [comment]
No more, closing.
